services:
  api:
    build: .
    container_name: school-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - school-network

  db:
    image: postgres:15-alpine
    container_name: school-db
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-school_db}
    ports:
      - "5433:5432" # Changement du port externe pour éviter les conflits
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school-network

networks:
  school-network:
    driver: bridge

volumes:
  postgres_data:
